@startuml
left to right direction
actor User
rectangle "Інформаційна система" {
  User -- (Управління проектами)
  User -- (Централізоване зберігання документів)
  User -- (Аналітики даних)
  User -- (Комунікація та співпраця)
  (Управління проектами) -- (Аналітики даних)
  (Управління проектами) -- (Комунікація та співпраця)
  (Централізоване зберігання документів) -- (Аналітики даних)
  (Централізоване зберігання документів) -- (Комунікація та співпраця)
  (Аналітики даних) -- (Комунікація та співпраця)
}
@enduml
